version: '3.9'

services:
  db:
    container_name: stonkseeker-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - ./backend/data:/var/lib/postgresql/data
      - ./backend/init_scripts:/docker-entrypoint-initdb.d