version: '3.9'

services:
  db:
    container_name: stockit_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
  init:
    image: python:latest
    volumes:
      - ./migration.py:migration.py
    entrypoint:
      - "python migration.py"