# Use the official postgres image from Docker Hub
FROM postgres

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Expose the PostgreSQL port
EXPOSE 5432

# Copy initialization scripts into the image
# COPY ./init_scripts /docker-entrypoint-initdb.d

# Specify the volume for persisting data
# VOLUME ["/var/lib/postgresql/data"]
