-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.posts DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.comments DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.stock_mentions DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public.posts;

CREATE TABLE IF NOT EXISTS public.posts
(
    id text NOT NULL,
    link text NOT NULL,
    subreddit_id text NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.comments;

CREATE TABLE IF NOT EXISTS public.comments
(
    id text NOT NULL,
    post_id text NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    permalink text NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.stock_mentions;

CREATE TABLE IF NOT EXISTS public.stock_mentions
(
    id serial NOT NULL,
    comment_id text NOT NULL,
    symbol character varying(5) NOT NULL,
    company_name text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.subreddits;

CREATE TABLE IF NOT EXISTS public.subreddits
(
    id text NOT NULL,
    name text,
    PRIMARY KEY (id),
    UNIQUE (name)
);

ALTER TABLE IF EXISTS public.posts
    ADD FOREIGN KEY (subreddit_id)
    REFERENCES public.subreddits (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comments
    ADD FOREIGN KEY (post_id)
    REFERENCES public.posts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.stock_mentions
    ADD FOREIGN KEY (comment_id)
    REFERENCES public.comments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;