# Use an official Python runtime as a parent image
FROM python:3.9.19-slim

# Set the working directory in the container to /app
WORKDIR /usr/src/app

# Add the current directory contents into the container at /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download en_core_web_sm

# Run app.py when the container launches
CMD ["python", "./v1/main.py"]