# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container to /app
WORKDIR /usr/src/app

# Add the current directory contents into the container at /app
COPY ./v1/ .

# RUN apt-get update && apt-get upgrade -y && apt-get install rsync -y

# RUN chmod +x ./v1/install_dependencies.sh && ./v1/install_dependencies.sh
RUN pip install pika psycopg[binary] asyncpg praw diskcache spacy axiom-py asyncpraw
RUN python -m spacy download en_core_web_sm
CMD ["python", "-u", "./main.py"]

# RUN chmod +x install.sh && ./install.sh

# Run app.py when the container launches
# CMD ["./install.sh"]