name: Start Python worker Daemon

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  start_daemon:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Kill old daemon
        run: sudo pkill -f "main copy.py"

      - name: Start new daemon
        run: ./worker/start.sh
